[theme]
# Inherit from the default light theme
base="light" 
# Set a dark text color for better contrast
textColor="#31333f" 
# Set a slightly different background color for the table header to make it stand out
secondaryBackgroundColor="#c1d3f5" 
# Ensure borders are visible
dataframeBorderColor="#575b78"
